ims/ims/addons/assets/urls.py
from django.conf import settings
from django.urls import re_path
from ims.addons.assets import views

app_name='ims.addons.assets'
urlpatterns = [
    re_path(r'^$', views.asset_list, name='asset_list'),
    re_path(r'^details/$', views.asset_details, name='asset_detail'),
]

ims/ims/addons/assets/models.py
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from itertools import chain
import logging

import ims.addons.assets.helpers as helpers
from inventory.models import Part, Storage, get_sentinel_part, get_sentinel_storage
from log.logger import getLogger

logger = logging.getLogger(__name__)
logger2 = getLogger('assets')

class Asset(models.Model):
    assetid = models.CharField(max_length=256)
    serialnumber = models.EmailField(max_length=256)
    part = models.ForeignKey('inventory.Part',on_delete=models.SET(get_sentinel_part),related_name='+')
    storage = models.ForeignKey('inventory.Storage',on_delete=models.SET(get_sentinel_storage),related_name='+')
    created = models.DateTimeField(auto_now_add=True,editable=False)
    lastmodified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['assetid','serialnumber']

    def __str__(self):
        return '{}-{}'.format(self.assetid, self.serialnumber)

    def get_absolute_url(self):
        logger.debug('Generating absolute URL for Asset id {}'.format(self.id))
        return reverse('ims.addons.assets:asset_detail', args=[self.id])

    def save(self, *args, **kwargs):
        if self.id != None:
            logger.info('Saving changes made to Asset id {}'.format(self.id))
        else:
            logger.info('Creating new Asset "{}"'.format(self))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        logger.info('Deleting Asset id {}'.format(self.id))
        super().delete(*args, **kwargs)

    def move(self, storage):
        try:
            if helpers.is_int(storage):
                storage = Storage.objects.get(id=storage)
            self.storage = storage
            self.save()
            logger.info('Moved Asset id {} to Storage id {}'.format(self.id, storage.id))
        except Storage.DoesNotExist as err:
            logger.warning('Unable to locate Storage \'{}\'. Error mesesage: {}'.format(storage, err))
            raise
        except Exception as err:
            logger.warning('There was an unknown problem in Asset.move() method.')
            logger.debug(err)
            raise

class CustomField(models.Model):
    name = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    required = models.BooleanField(default=False)
    regex = models.TextField()
    widget = models.CharField(max_length=2,choices=helpers.WIDGETS,default=helpers.TEXTINPUT)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if self.id != None:
            logger.info('Saving changes made to CustomField id {}'.format(self.id))
        else:
            logger.info('Creating new CustomField "{}"'.format(self))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        logger.info('Deleting CustomField id {}'.format(self.id))
        super().delete(*args, **kwargs)

class AssetDetail(models.Model):
    asset = models.ForeignKey(Asset,on_delete=models.CASCADE,related_name='details',related_query_name='detail')
    customfield = models.ForeignKey(CustomField,on_delete=models.CASCADE,related_name='+')
    value = models.TextField()

    class Meta:
        ordering = ['asset','customfield']

    def __str__(self):
        return '{}-{}'.format(self.asset.name, self.customfield.name)

    def save(self, *args, **kwargs):
        if self.id != None:
            logger.info('Saving changes made to AssetDetail id {}'.format(self.id))
        else:
            logger.info('Creating new AssetDetail "{}"'.format(self))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        logger.info('Deleting AssetDetail id {}'.format(self.id))
        super().delete(*args, **kwargs)

ims/ims/addons/assets/forms.py
from datetime import datetime
from django import forms
from django.contrib.auth.models import User

ims/ims/addons/assets/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
import logging

from inventory.search import Search
import ims.addons.assets.helpers as helpers
from ims.addons.assets.models import Asset, AssetDetail, CustomField
from log.logger import getLogger

logger = logging.getLogger(__name__)
logger2 = getLogger('tracker')

def asset_list(request):
    cname = 'asset_list'
    logger.debug('Request made to {} view'.format(cname))
    logmsg = 'Accessed Asset List'
    logger2.debug((request.user or 0), 'Request to view {}'.format(cname))
    if settings.ALLOW_ANONYMOUS or request.user.is_authenticated:
        # Get all PartThreshold
        logger.debug('Generating object_list of Assets')
        object_list = Asset.objects.all()

        # Create the Search filter and apply to the existing results
        query = request.GET.get('q')
        if query != None: 
            logger.debug('Filtering object_list of Assets with query')
            logmsg = '{} with query \'{}\''.format(logmsg, query)
            querytype = request.GET.get('t')
            qt = helpers.parse_querytype(querytype)
            sf = Search().filter(['name', 'detail__value', 'description'], qt + query)
            object_list = object_list.filter(sf)

        # Create the Paginator and get the existing page
        logger.debug('Paginate object_list of Asset')
        paginator = Paginator(object_list, settings.ADDON_ASSETS_PAGE_SIZE)
        page = request.GET.get('page')
        try:
            assets = paginator.page(page)
        except PageNotAnInteger:
            logger.debug('PageNotAnInteger, show page 1')
            assets = paginator.page(1)
        except EmptyPage:
            logger.debug('EmptyPage, show page {}'.format(paginator.num_pages))
            assets = paginator.page(paginator.num_pages)

        # Return the list of partthresholds
        logger.debug('Rendering request for {} view'.format(cname))
        logger2.info((request.user or 0), logmsg)
        return render(request, 'assets/list.html', {'query': query, 'page': page, 'assets': assets})
    else:
        logger.debug('User was not authenticated and ALLOW_ANONYMOUS is set to False')
        logger2.warning(0, 'Unauthenticated request to {}'.format(request.path))
        return redirect('/accounts/login/?next=' + request.path)
    
def asset_detail(request, id):
    cname = 'asset_detail'
    logger.debug('Request made to {} view'.format(cname))
    logger2.debug((request.user or 0), 'Request to view Asset Details for id {}'.format(id))
    if settings.ALLOW_ANONYMOUS or request.user.is_authenticated:
        # Get the Asset object to display in detail
        asset = get_object_or_404(Asset, id=id)
        logger.debug('Rendering request for {} view'.format(cname))
        logger2.info((request.user or 0), 'Accessed Asset id {}'.format(id))
        return render(request, 'assets/detail.html', {'asset': asset})
    else:
        logger.debug('User was not authenticated and ALLOW_ANONYMOUS is set to False')
        logger2.warning(0, 'Unauthenticated request to {}'.format(request.path))
        return redirect('/accounts/login/?next=' + request.path)

def ajax_asset_move(request, id, sid):
    pass

ims/templates/assets/admin/create.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}New {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/assets/admin/" alt="Assets Admin">Assets Admin</a>
    »
    <a href="/assets/admin/{{ name|lower }}/" alt="Assets Admin {{ name }}">{{ name }}</a>
    » Add {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>New {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/assets/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ims/templates/assets/admin/home.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Assets Admin{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Assets Admin</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col l12 xl6 w3-card w3-padding w3-bar-block">
            <div class="w3-bar-item">
                {% if perms.assets.view_asset %}<a class="w3-button ims-form-field" href="/assets/admin/asset/">Asset</a>{% endif %}
                {% if perms.assets.view_assetdetail %}<a class="w3-button ims-form-field" href="/assets/admin/assetdetail/">AssetDetail</a>{% endif %}
                {% if perms.assets.view_customfield %}<a class="w3-button ims-form-field" href="/assets/admin/customfield/">CustomField</a>{% endif %}
            </div>
	</div>
    </div>
</div>
{% endblock %}

ims/templates/assets/admin/update.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Update {{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/assets/admin/" alt="Assets Admin">Assets Admin</a>
    »
    <a href="/assets/admin/{{ objtype|lower }}/" alt="Assets Admin {{ objtype }}">{{ objtype }}</a>
    » {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>Update {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/assets/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ims/templates/assets/admin/view.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load static %}
{% block title %}{{ name }}{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/assets/admin/" alt="Assets Admin">Assets Admin</a>
    » {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>{{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div id="message" class="w3-col w3-padding w3-left"></div>
    </div>
    <div class="w3-container">
        <div class="w3-card w3-padding w3-left w3-col l12 xl6">
            {% if 'assets.add_{{ name|lower }}' in perms %}<div class="w3-right w3-padding"><a href="/assets/admin/{{ name|lower }}/create/" alt="Add {{ name }}" class="w3-button w3-hover-green w3-round w3-col w3-border">+ New</a></div>{% endif %}
            {% for obj in objs %}
            <div id="{{ obj.id }}" class="w3-card w3-padding w3-left w3-col">
                <div class="w3-left"><b>{{ obj }}</b></div>
                <div class="w3-right">
                    {% if 'assets.delete_{{ name|lower }}' in perms %}<div class="w3-right"><a href="javascript:void(0)" alt="Delete {{ name }}-{{ obj.id }}" class="w3-hover-red w3-button w3-round w3-border" onclick="delobj({{ obj.id }})">- Delete</a></div>{% endif %}
                    {% if allowupdate %}{% if 'assets.change_{{ name|lower }}' in perms %}<div class="w3-right"><a href="/assets/admin/{{ name|lower }}/change/{{ obj.id }}/" alt="Update {{ name }}-{{ obj.id }}" class="w3-button w3-hover-green w3-round w3-border w3-margin-right">Update</a></div>{% endif %}{% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% include "inventory/pagination.html" with page=objs %}
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    function delobj(id) {
        var parentdiv = document.getElementById(id);
        $.ajax({
            url: '/assets/admin/{{ name|lower }}/delete/' + id + '/',
            type: 'get',
            success: function(data) {
                if (data.includes('green')) { parentdiv.classList.add('ims-hidden'); }
                $("#message").html(data);
            }
        });
    }
</script>
{% endblock %}
{% block sidebar %}
<div id="search" class="ims-admin-search-bar w3-padding w3-card">
    <form method="get" style="margin:0;">
        <input type="text" placeholder="search for {{ name|lower }}" name="q"{% if query %} value="{{ query }}"{% endif %}/>
        <button class="w3-button" type="submit">Search</button>
    </form>
</div>
<script>
    var scroll_direction = true;
    window.addEventListener("resize", scroll_check);
    var prev_scroll_pos = window.pageYOffset;
    var elem = document.getElementById("search");
    window.onscroll = function() {
        if (scroll_direction) {
            var current_scroll_pos = window.pageYOffset;
            if (prev_scroll_pos > current_scroll_pos) {
                elem.style.top = "43px";
            } else {
                elem.style.top = "-15px";
            }
            prev_scroll_pos = current_scroll_pos;
	} else {
            var current_scroll_pos = window.pageYOffset;
            if (prev_scroll_pos > current_scroll_pos) {
                elem.style.visibility = "visible";
            } else {
                elem.style.visibility = "hidden";
            }
            prev_scroll_pos = current_scroll_pos;
        }
    }
    function scroll_check() {
        var w = window.innerWidth;
        if (w > 639) { 
            scroll_direction = true;
            elem.style.bottom = null;
            elem.style.top = "43px";
        } else {
            scroll_direction = false;
            elem.style.top = null;
            elem.style.bottom = "0";
        }
        elem.style.visibility = "visible";
    }
</script>
{% endblock %}

ims/templates/assets/asset/detail.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load static %}

{% block title %}{{ asset.assetid }}{% endblock %}

{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left">
        <h4>{{ asset.assetid }}</h4>
    </div>
    <div class="w3-container">
        <div id="message" class="w3-col w3-padding w3-left"></div>
    </div>
    <div class="w3-container w3-margin-bottom">
        <div id="id_partdetail" class="w3-card w3-padding w3-left w3-col l6">
            <div class="w3-small">{{ asset.serialnumber }}</div>
            <div class="w3-left"><b>Part:</b> ${{ asset.part }}</div>
            <div class="w3-right"><b>Storage:</b> ${{ asset.storage }}</div>
        </div>
    </div>
    <div class="w3-container w3-margin-bottom">
        <div class="w3-card w3-padding w3-left w3-col l6">
            <div class="w3-left"><h5><b>Asset Details</b></h5></div>
            {% if perms.assets.can_add_assetdetail %}
            <div class="w3-right">
                <a href="/assets/admin/assetdetail/create/?asset={{ asset.id }}" alt="Add to Details" class="w3-button w3-hover-green w3-round w3-border">+ New</a>
            </div>
            {% endif %}
            {% if asset.has_details %}
            {% for detail in asset.get_details %}
            <div class="w3-card w3-padding"{% if forloop.first %} style="margin-top:50px;"{% endif %}>
                <div class="w3-left"><b>{{ detail.customfield.name }}</b></div>
                <div class="w3-right">{{ detail|render_customfield }}</div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    function moveasset(id) {
        $.ajax({
            url: '/inventory/partstorage/' + id + '/add/1/',
            type: 'get',
            success: function(data) {
                $("#message").html(data);
                $.ajax({
                    url: '/inventory/partstorage/' + id + '/update/psstorage/',
                    type: 'get',
                    success: function(data) {
                        $("#id_" + id).html(data);
                    }
                });
            }
        });
    }
</script>
{% endblock %}

ims/templates/assets/asset/list.html
{% extends "inventory/base.html" %}
{% load get_setting %}

{% block title %}Parts List{% endblock %}

{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Assets List</b></h4>
    </div>
    {% if perms.inventory.can_add_part %}
    <div class="w3-right">
        <a href="/assets/admin/asset/create/" alt="Add Asset" class="w3-button w3-hover-green w3-round w3-border">+ New</a>
    </div>
    {% endif %}
    <div class="w3-container">
        {% for asset in assets %}
        <div class="w3-col l12 xl6 w3-card w3-padding">
            <a href="{{ asset.get_absolute_url }}" class="w3-medium" alt="View Asset {{ asset.assetid }}">{{ asset.assetid }}</a>
            <a href="javascript:void(0)" onclick="ims_expand(this)" class="w3-button w3-right" alt="Expand information for {{ asset.assetid }}">+</a>
            <div class="w3-col w3-card w3-padding ims-hidden">
                <div class="w3-left w3-col w3-small">{{ asset.serialnumber }}</div>
                <div class="w3-left"><u>Part:</u> ${{ asset.part }}</div>
                <div class="w3-right"><u>Storage:</u> ${{ asset.storage }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
{% include "inventory/pagination.html" with page=assets %}
</div>
<script>
    function ims_expand(elem) {
        var parent = elem.parentNode;
        var child_div = parent.getElementsByTagName("div")[0];
        if (elem.text === "+") {
            elem.text = "-";
            child_div.classList.remove("ims-hidden");
        } else {
            elem.text = "+";
            child_div.classList.add("ims-hidden");
        }
    }
</script>
{% endblock %}
{% block sidebar %}
<div id="search" class="ims-search-bar w3-padding w3-card" style="top:43px;">
    <form method="get" style="margin:0;">
        <input type="text" placeholder="search for assets" name="q"{% if query %} value="{{ query }}"{% endif %}/>
        <button class="w3-button" type="submit">Search</button>
    </form>
</div>
<script>
    var prev_scroll_pos = window.pageYOffset;
    window.onscroll = function() {
        var current_scroll_pos = window.pageYOffset;
        var elem = document.getElementById("search");
        if (prev_scroll_pos > current_scroll_pos) {
            elem.style.top = "43px";
        } else {
            elem.style.top = "-15px";
        }
        prev_scroll_pos = current_scroll_pos;
    }
</script>
{% endblock %}